name: My cowsay ascii Workflow

on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install-dependent-packages
        run: sudo apt-get update && sudo apt install cowsay -y

      - name: run the cowsay
        run: cowsay -f dragon "hello RRRR" >> dragon.txt

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon.txt file
          path: dragon.txt
  Test_job:
    needs: build_job
    runs-on : ubuntu-latest
    steps:
      - name: Download an artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon.txt file

      - name: Display structure of downloaded files
        run: ls -R
        
  Deploy_job:
    needs: [build_job, Test_job]
    runs-on : ubuntu-latest
    steps:
      - name: Download an artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon.txt file
      - name: read the file
        run: cat dragon.txt
