name: My cowsay ascii Workflow

on: push

jobs:
  Ascii_flow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ASCII packages
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Run cowsay command
        run: cowsay -f dragon "Hello rrrrr" >> dragon.txt

      - name: Verify the dragon file
        run: grep -i "dragon" dragon.txt

      - name: Read the file
        run: cat dragon.txt

      - name: List the files
        run: ls -ltra
