name: My cowsay ascii Workflow

on: push

jobs:
  Ascii_flow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: list the files
        run: ls -ltra

      - name: Executing shell script
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh
