name: My cowsay ascii Workflow

on: push

jobs:
    Ascii_flow:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: installing-ASCII-packages
          run: |
            sudo apt-get update
            sudo apt install cowsay -y

        - name: Cowsay-command
          run: cowsay -f dog "hellow rrrrr" >> dog.txt

        - name: find the dragon file
          run: grep -i "dog" dog.txt

        - name: read the file
          run: cat dog.txt

        - name: list the  files
          run: ls -ltra
