name: My cowsay ascii Workflow

on: push

jobs:
    Ascii_flow:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: welcome message
          run: |
            echo "my first github actions job"
            ls -ltra
            cat readme.md

        - name: installing-ASCII-packages
          run: |
            sudo apt-get update
            sudo apt install cowsay -y
        - name: Cowsay-command
          run: cowsay -f dragon "hellow rrrrr" >> dragon.txt

        - name: find the dragon file
          run: grep -i "dragon.txt"

        - name: read the file
          run: cat dragon.txt
