name: My cowsay ascii Workflow

on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_repo
        uses: actions/checkout@v4

      - name: list files
        run: ls -ltra

      - name: Install-dependent-packages
        run: sudo apt-get update && sudo apt install cowsay -y

      - name: run the cowsay
        run: cowsay -f dragon "hello RRRR" >> dragon.txt

      - name: Sleep fpr 30 sec
        run: sleep 30
  Test_job:
    needs: build_job
    runs-on : ubuntu-latest
    steps:
      - name: Sleep fpr 10 sec
        run: sleep 10

      - name: Find the dragon file
        run: grep "dragon" dragon.txt
  Deploy_job:
    needs: [build_job, Test_job]
    runs-on : ubuntu-latest
    steps:
      - name: read the file
        run: cat dragon.txt
