name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: welcome message
          run: |
            echo "my first github actions job"
            ls-ltra
            cat readme.md

        - name: cowsay command_ASCII
          run: |
            apt-get update
            apt-install cowsay -y
            cowsay -f dragon "hellow rrrrr"

          


        # - name: List files
        #   run: ls

        # - name: Read file
        #   run: cat readme.md
